friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/modules/woocommerce/index.php
friendly-captcha/modules/woocommerce/woocommerce_checkout.php
friendly-captcha/modules/woocommerce/woocommerce_login.php
friendly-captcha/modules/woocommerce/woocommerce_lost_password.php
friendly-captcha/modules/woocommerce/woocommerce_register.php
friendly-captcha/readme.txt

This adds WooCommerce support to this plugin. 
WooCommerce Login Form:
WooCommerce Register Form:
WooCommerce Lost Password Form:
WooCommerce Checkout Form:
Settings Form: 
Closes #7

Add WooCommerce support

---

friendly-captcha/modules/ultimate-member/ultimate-member_login.php
friendly-captcha/modules/ultimate-member/ultimate-member_register.php
friendly-captcha/modules/ultimate-member/ultimate-member_reset_password.php
friendly-captcha/modules/woocommerce/woocommerce_checkout.php
friendly-captcha/modules/woocommerce/woocommerce_login.php
friendly-captcha/modules/woocommerce/woocommerce_register.php

Since ultimate members uses the same action for both the login and the registration form, this action was called twice on every login. This caused a duplication error by friendly captcha. 
This PR fixes this by wrapping the action with a condition, that checks which form is used.

Fix ultimate member captcha verification

---

friendly-captcha/modules/wordpress/wordpress_login.php

I realized, that the UM integration still did not work when the native wordpress login form integration was active as well, so I debugged a little bit.
It seems, that UM integrated with the native wordpress login hook:
https://github.com/ultimatemember/ultimatemember/blob/df4d0c3543d7d22e067fa89f10a32eeec5e9604a/includes/core/um-actions-login.php#L66
which is also triggered here:
https://github.com/FriendlyCaptcha/friendly-captcha-wordpress/blob/8c02f58b6bce5dbf04fba6c8ab0a510d064cf084/friendly-captcha/modules/wordpress/wordpress_login.php#L19
So when UM starts a verification request, this hook will also start another verification request, which leads to captcha errors. 
~~I fixed this by checking, if the request was made by UM or not and in case it was made by UM I ignore it and do not …

Fix ultimate member double captcha request when WP login captcha is active as well

---

friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/modules/elementor/elementor.php
friendly-captcha/modules/elementor/field.php
friendly-captcha/modules/elementor/index.php

We previously had issues implementing an integration for Elementor because their documentation was insufficient. Specifically the documentation for adding new form fields was missing, this was recently resolved and can be found here: https://developers.elementor.com/docs/form-fields/
closes #28
closes #14

Elementor Pro Forms Integration

---

friendly-captcha/modules/contact-form-7/contact-form-7.php

Hello,
i know that this is not the most inclusive thing to do but i just had another customer who was confused why FC wouldn't just flag emails as spam when you have javascript deactivated and to be fair i was confused about that as well. 
So the issue is, that the FC Server responses with a 401 Statuscode when you send an empty solution to it but in the CF7 Module everything that is not a 200 Statuscode will get a "success". 
```php
if ( 200 != $status ) {
if ( WP_DEBUG ) {
frcaptcha_log_remote_request( $endpoint, $request, $response );
// error_log("The body was " . $body);
}
// Better safe than sorry, if the request is non-200 we can not verify the response
// Either the user's credentials are wrong (e.g. wrong sitekey, api key) or the friendly
// captcha servers are unresponsive.
// …
```

If Javascript has been deactivated, we wan't to flag it as spam (In Contact Form 7)

---

friendly-captcha/modules/gravityforms/field.php

As described in #70 some wordpress themes don't call the `wp_footer` hook and our gravity forms integration therefore doesn't work with them.
To fix this I just enqueue the scripts directly when the form field is generated. It shouldn't matter when the scripts are enqueued because wordpress takes care of loading them at the right time. Enqueuing them multiple times is also not an issue.
According to the Wordpress docs for wp_enqueue_script:
> Links a script file to the generated page at the right time according to the script dependencies, if the script has not been already included and if all the dependencies have been registered.
fixes #70

Fix Gravity Forms issue

---

friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/public/widgets.php

This PR adds a new plugin setting which allows users to disable the injection of our CSS styles. This was requested by a customer.
It works by injecting an element with the id `frc-style` which is checked for by widget: https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/dom.ts#L110
closes #66

Add setting to disable style injection

---

friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/modules/html-forms/html-forms.php
friendly-captcha/modules/html-forms/index.php
friendly-captcha/readme.txt

This PR adds integration for [HTML Forms](https://de.wordpress.org/plugins/html-forms/).
closes #68

add html forms integration

---

friendly-captcha/modules/gravityforms/field.php
friendly-captcha/modules/gravityforms/script.js

I'm basically re-running the setup() function from https://github.com/FriendlyCaptcha/friendly-challenge/blob/master/src/main.ts when the form page is changed. This way we can find widgets that are added on later pages.
closes #74

Fix gravity forms integration for multi-page forms with ajax

---

friendly-captcha/includes/verification.php
friendly-captcha/modules/gravityforms/field.php
friendly-captcha/readme.txt

Before this PR `error_codes` in the return value of `frcaptcha_verify_captcha_solution` was a string when there was an error and an empty array if there was non. Some functions were calling `next()` on that value which caused an PHP error.

Fix error codes being a string

---

friendly-captcha/readme.txt

I have tested the plugin with the newest beta release of Wordpress 6.2.
@dev-love Do I need to update the version somewhere else as well? Where does it pull the 6.1.1 on the plugin site from? I couldn't find anything in the code 🤔

Prepare for new wordpress version 6.2

---

friendly-captcha/modules/wordpress/wordpress_login.php
friendly-captcha/modules/wordpress/wordpress_register.php
friendly-captcha/modules/wordpress/wordpress_reset_password.php

According to the documentation of the `authenticate` hook we should return the `$user` variable if we want the login to succeed. Before this PR we returned nothing when the plugin is not configured correctly which will cause the authentication to fail. This is not what we want

Fix integration for wordpress login, register, and forgot password

---

friendly-captcha/modules/wordpress/wordpress_login.php

Because the `authenticate` hook is being called for the first time when the page is loaded it would always display an error because the `POST` body would be empty. Now we check if there is already an error (which seems to be product by WP for GET requests) and then return that.
fixes #97 
https://wordpress.stackexchange.com/a/395662

Fix login error being displayed on page load

---

friendly-captcha/modules/avada-forms/avada-forms.php

Avada forms seems to put all form fields under the `formData` key as url encoded args. This can also be seen in the hcaptcha integration: https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/master/src/php/Avada/Form.php#L88-L93
These changes have only been tested for syntactic errors.

fix avada form integration

---

friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/modules/contact-form-7/contact-form-7.php

A customer has reported that our plugin doesn't work together with the Forge12 Contact Form 7 Double Opt-In plugin. I think this is because the plugin triggers a second form submit after clicking the opt-in link in the email which is rejected by our plugin because of the missing captcha solution.
I have added a new setting to let this second submit bypass the captcha check. This happens by checking if it's a GET request (not the case for normal form submits) and if the `optin` query parameter is set. As this is not a perfect check and may open some unforeseen security holes users have to explicitly enable this.

Add support for f12 cf7 double opt in

---

friendly-captcha/includes/core.php
friendly-captcha/includes/settings.php
friendly-captcha/public/mutation-observer.js
friendly-captcha/public/widgets.php

This PR introduces a new settings which allows our plugin to initialize widgets that are dynamically added to the page after load. This includes popups, multi-step forms and generally content loaded with AJAX.
We achieve this by adding a MutationObserver to the document body which looks for new nodes being added to the DOM. It then initializes any element with the `.frc-captcha` class if it doesn't have the `friendlyChallengeWidget` property which is added by the friendly-challenge library.
We look for the `friendlyChallengeWidget` property instead of the `data-attached` attribute because the latter persists when HTML is removed and added back to the DOM.
This is opt-in because it could potentially affect the performance of the page. After all we are running a bit of code whenever a new …

Initialize widgets that are dynamically added to the page

---

friendly-captcha/friendly-captcha.php
friendly-captcha/includes/core.php
friendly-captcha/readme.txt

With PHP 8.1 passing null to inbuilt functions is deprecated. See https://wiki.php.net/rfc/deprecate_null_to_scalar_internal_arg
We have previously used `defined` to check if the singleton instance of our plugin class has already been created. `defined` expects a string and is not meant to be used for checking if a variable is set. 
In practice this has probably caused the check to always return false and the class to be recreated every time. We just never noticed because before PHP 8.1 this was just ignored.

Fix deprecation error in PHP 8.1 and above

---

friendly-captcha/modules/contact-form-7/script.js
friendly-captcha/modules/elementor/field.php
friendly-captcha/modules/elementor/script.js
friendly-captcha/modules/wpforms/script.js
friendly-captcha/modules/wpforms/wpforms.php

Reset the widget after the form has been submitted (both successful or unsuccessful) so users can submit again. This was requested by customers because users were having problems resubmitting a form after the field validation has failed because the FC solution has already been used.
The script used for elementor can potentially used for any form plugin that doesn't prevent the default submit event. (wpforms does prevent it) I only tested it with elementor and it might somehow break other form plugins tho
I'm not entirely sure if this should be default behavior or opt in as it might lead to more spam submissions. What do you think @gzuidhof?

Reset widgets after submission in contact form 7, WPForms & Elementor

---

.gitignore
friendly-captcha/.gitignore

With the `.gitignore` moved to the root folder the vendor folder is still ignored from our version control but won't be ignored after installing the plugin (which only includes the `friendly-captcha` folder) into a Wordpress site. This way users can have their Wordpress site in version control together with all the dependencies. 
fixes #128

Move gitignore to root folder

---

friendly-captcha/friendly-captcha.php
friendly-captcha/includes/core.php
friendly-captcha/modules/divi/frcaptcha_divi_core_addon.php
friendly-captcha/modules/formidable/FrcaptchaFieldNewType.php
friendly-captcha/modules/profile-builder/profile_builder_login.php
friendly-captcha/modules/profile-builder/profile_builder_register.php
friendly-captcha/modules/profile-builder/profile_builder_reset_password.php
friendly-captcha/modules/woocommerce/woocommerce_checkout.php
friendly-captcha/modules/woocommerce/woocommerce_login.php
friendly-captcha/modules/woocommerce/woocommerce_register.php
friendly-captcha/modules/wpforms/wpforms.php
friendly-captcha/readme.txt

This was already the case for most integrations, some were just missing an early return. Submitting them to the siteverify endpoint would return a non-200 response code and an unnecessary error alert.

Don't call siteverify when Captcha solution is empty

---

friendly-captcha/modules/wordpress/wordpress_login.php

The Wordfence code is a bit hard to follow, but I tried the positive and negative cases and it behaves as expected now. 
One other thing I noticed is that our `authenticate` filter is run after the credentials have been verified. I believe we should try to change it so the Captcha is verified before the credentials, right?
closes #144

Skip second call of authenticate filter when Wordfence 2FA is enabled

---

friendly-captcha/friendly-captcha.php
friendly-captcha/modules/wordpress/wordpress_login.php
friendly-captcha/readme.txt

We changed the filter for WordPress Login from 'authenticate' to 'wp_authenticate_user'. We need to also update the logic that removes that filter when Ultimate Member is in use; otherwise the verification method call happens twice. The second time it fails with `response_duplicate`.

Remove the correct filter when using Ultimate Member

---

friendly-captcha/friendly-captcha.php
friendly-captcha/modules/elementor/elementor.php
friendly-captcha/modules/elementor/field.php
friendly-captcha/readme.txt

I suspect that the `render` method of a custom Elementor field is only called once and then the result is cached which leads to the weird behavior where Friendly Captcha loads in some cases but doesn't in others.
I have moved the enqueuing of the Friendly Captcha scripts to the `elementor/init` hook which should always be called. This also means the Friendly Captcha scripts are loaded on every page using Elementor but I think that's OK. [hCaptcha does the same.](https://github.com/hCaptcha/hcaptcha-wordpress-plugin/blob/master/src/php/ElementorPro/HCaptchaHandler.php#L84-L113)
#139

Enqueue friendly captcha scripts on elementor init

---

friendly-captcha/composer.json
friendly-captcha/composer.lock
friendly-captcha/friendly-captcha.php
friendly-captcha/includes/verification.php
friendly-captcha/modules/avada-forms/avada-forms.php
friendly-captcha/modules/coblocks/coblocks.php
friendly-captcha/modules/contact-form-7/contact-form-7.php
friendly-captcha/modules/divi/frcaptcha_divi_core_addon.php
friendly-captcha/modules/elementor/field.php
friendly-captcha/modules/fluentform/fluentform.php
friendly-captcha/modules/formidable/FrcaptchaFieldNewType.php
friendly-captcha/modules/forminator/forminator.php
friendly-captcha/modules/gravityforms/field.php
friendly-captcha/modules/html-forms/html-forms.php
friendly-captcha/modules/profile-builder/profile_builder_login.php
friendly-captcha/modules/profile-builder/profile_builder_register.php
friendly-captcha/modules/profile-builder/profile_builder_reset_password.php
friendly-captcha/modules/ultimate-member/ultimate-member_login.php
friendly-captcha/modules/ultimate-member/ultimate-member_register.php
friendly-captcha/modules/ultimate-member/ultimate-member_reset_password.php
friendly-captcha/modules/woocommerce/woocommerce_checkout.php
friendly-captcha/modules/woocommerce/woocommerce_login.php
friendly-captcha/modules/woocommerce/woocommerce_register.php
friendly-captcha/modules/wpforms/wpforms.php
friendly-captcha/modules/wpum/wpum_validate.php
friendly-captcha/readme.txt

This PR adds support for passing the `Frc-Sdk` header in siteverify requests, for measuring SDK usage.

Add support for passing "Frc-Sdk" header

---

friendly-captcha/modules/wordpress/wordpress_comments.php

WooCommerce reviews use the WordPress comment system but have set the `comment_type` to `review`.

Verify captcha on WooCommerce reviews
